version: '3'
services:
  web:
    container_name: "shadow-cljs-node.js"
    volumes:
      - ..:/workspaces/markdownify:cached
    build: .

    ports:
      - '9090:9090' # shadow-cljs - HTTP server available at http://localhost:9090
      - '9630:9630' # shadow-cljs - server version: 2.8.83 running at http://localhost:9630
    command: tail -f /dev/null
